name: Test application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # Test full project
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: |
          go test -v ./...